using System.Collections;
using FirstExample.ExampleProject;
using NUnit.Framework;

namespace FirstExample.ExampleProject.Test
{
    [TestFixture]
    public class ExampleClassTests
    {
        [Test]
        public void SumTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void DesTest()
        {
            Assert.Fail("autogenerated");
        }

        [Test]
        public void MulTest()
        {
            Assert.Fail("autogenerated");
        }
    }
}